# Generated by Django 3.2.4 on 2021-06-20 15:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.UUIDField(default=uuid.uuid4, help_text='Код кдиента', primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Фамилия', max_length=100)),
                ('last_name', models.CharField(help_text='Имя', max_length=100)),
                ('addres', models.CharField(help_text='Имя', max_length=100)),
                ('telephon', models.CharField(help_text='Введите номер телефона 11 чисел', max_length=11)),
                ('id_pass', models.CharField(help_text='Введите серию и номер паспорта', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Oborudovanie',
            fields=[
                ('id_oborud', models.UUIDField(default=uuid.uuid4, help_text='Код оборудования', primary_key=True, serialize=False)),
                ('name_oborud', models.CharField(help_text='Название оборудование', max_length=100)),
                ('type_oborud', models.CharField(help_text='Тип оборудования', max_length=100)),
                ('date_of_priem', models.DateField(blank=True, null=True, verbose_name='приема')),
                ('date_of_sdachi', models.DateField(blank=True, null=True, verbose_name='сдачи')),
            ],
        ),
        migrations.CreateModel(
            name='Vozvrat',
            fields=[
                ('id_voz', models.UUIDField(default=uuid.uuid4, help_text='Код возврата', primary_key=True, serialize=False)),
                ('nomer_doc', models.CharField(help_text='Номер документа', max_length=100)),
                ('status_oborudovania', models.CharField(blank=True, choices=[('m', 'Отличное'), ('n', 'Хорошее'), ('b', 'Плохое')], default='m', help_text='Статус оборудования', max_length=1)),
                ('id_oborud', models.UUIDField(default=uuid.uuid4, help_text='Код оборудования')),
                ('id_client', models.UUIDField(default=uuid.uuid4, help_text='Код кдиента')),
                ('shtraf', models.CharField(help_text='Размер штрафа', max_length=10)),
            ],
        ),
    ]
